//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// MissionManager.rc에서 사용되고 있습니다.
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MISSIONMANAGER_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       130
#define IDD_VERSIONLIST_DIALOG          132
#define IDD_MISSIONMANAGE_DIALOG        134
#define IDD_MISSION_ADD_DIALOG          137
#define IDD_MISSION_START_DIALOG        140
#define IDD_MISSIONLIST_DIALOG          142
#define IDD_SETTING_EVENT_DIALOG        145
#define IDD_MISSION_COUNT_SETTING_DIALOG 148
#define IDD_MISSION_TIMER_DIALOG        151
#define IDR_WAVE_ALARM                  154
#define IDC_BUTTON_MAIN_MISSION_START   1000
#define IDC_BUTTON_MAIN_MISSION_MANAGE  1001
#define IDC_BUTTON_MAIN_VERSION_SELECT  1002
#define IDC_STATIC_VERSION_NAME         1003
#define IDC_LIST_MAIN_MISSION_LIST      1004
#define IDC_LIST_ALL_VERSION_LIST       1005
#define IDC_LIST_MISSION_MANAGE         1006
#define IDC_BUTTON_MANAGE_SAVE          1007
#define IDC_BUTTON_MANAGE_CLOSE         1008
#define IDC_BUTTON_MANAGE_MISSION_ADD   1009
#define IDC_STATIC_INPUT_GROUP          1010
#define IDC_STATIC_MISSION_NAME         1011
#define IDC_EDIT_MISSION_NAME           1012
#define IDC_STATIC_EVENT_TYPE           1013
#define IDC_COMBO_EVENT_TYPE            1014
#define IDC_STATIC_RANDOM_OUTPUT        1015
#define IDC_LIST_RANDOM_OUTPUT_LIST     1019
#define IDC_EDIT_RANDOM_OUTPUT          1020
#define IDC_STATIC_RANDOM_VALUE_INPUT   1021
#define IDC_EDIT_MANAGE_VERSION_NAME    1022
#define IDC_STATIC_MANAGE_VERSION_NAME  1023
#define IDC_EDIT_ADD_MISSION_NAME       1024
#define IDC_COMBO_ADD_EVENT_TYPE        1025
#define IDC_LIST_ADD_RANDOM_INPUT_LIST  1026
#define IDC_EDIT_ADD_RANDOM_VALUE_INPUT 1027
#define IDC_BUTTON_ADD_SAVE             1028
#define IDC_MFCBUTTON2                  1029
#define IDC_BUTTON_ADD_CLOSE            1029
#define IDC_BUTTON_TIMER                1029
#define IDC_BUTTON_EXACT                1029
#define IDC_BUTTON_TIMER_RESET          1029
#define IDC_STATIC_ADD_MISSION_NAME     1030
#define IDC_STATIC_ADD_MISSION_EVENT_TYPE 1031
#define IDC_STATIC_ADD_RANDOM_INPUT_LIST 1032
#define IDC_STATIC_ADD_RANDOM_VALUE_INPUT 1033
#define IDC_BUTTON_START_EXTRACT        1034
#define IDC_EDIT_MISSION_PERFORMER      1035
#define IDC_STATIC_MISSION_PERFORMER    1036
#define IDC_STATIC_GROUP_EVENT          1038
#define IDC_LIST_EVENT_RANDOM_LIST      1040
#define IDC_BUTTON_EVENTSET_SAVE        1041
#define IDC_EDIT_EVENT_TEXT             1042
#define IDC_STATIC_EVENT_TEXT           1043
#define IDC_STATIC_HAVING_MISSION       1044
#define IDC_STATIC_HAVING_SHEILD        1045
#define IDC_BUTTON_SHEILD_EXTRACT       1046
#define IDC_STATIC_MISSION_START_MISSION_VIEW 1047
#define IDC_STATIC_MISSION_START_MISSION_VIEW_STATIC 1048
#define IDC_RADIO_MANAGE_LEVEL_EASY     1049
#define IDC_RADIO_MANAGE_LEVEL_         1050
#define IDC_RADIO_MANAGE_LEVEL_NORMAL   1050
#define IDC_RADIO3                      1051
#define IDC_RADIO_MANAGE_LEVEL_HARD     1051
#define IDC_RADIO_ADD_MISSION_LEVEL_HARD 1051
#define IDC_STATIC_GROUP_MANAGE_MISSION_GRADE 1052
#define IDC_RADIO_ADD_MISSION_LEVEL_EASY 1053
#define IDC_RADIO_ADD_MISSION_LEVEL_NORMAL 1054
#define IDC_STATIC_ADD_MISSION_GRADE    1055
#define IDC_STATIC_START_GROUP_COUNT    1056
#define IDC_STATIC_START_OUT_COUNT      1057
#define IDC_STATIC_START_SHEILD_COUNT   1058
#define IDC_BUTTON_START_COUNT_SET      1059
#define IDC_STATIC_START_OUT_COUNT_VIEW 1060
#define IDC_STATIC_START_SHEILD_COUNT_VIEW 1061
#define IDC_BUTTON_START_OUT_COUNT_UP   1062
#define IDC_BUTTON_START_OUT_COUNT_DOWN 1063
#define IDC_BUTTON_START_SHEILD_COUNT_UP 1064
#define IDC_BUTTON_START_SHEILD_COUNT_DOWN 1065
#define IDC_EDIT_COUNT_OUT              1066
#define IDC_EDIT_COUNT_SHEILD           1067
#define IDC_BUTTON_COUNT_SAVE           1068
#define IDC_STATIC_COUNT_GROUP          1069
#define IDC_STATIC_COUNT_OUT            1070
#define IDC_STATIC_COUNT_SHEILD         1071
#define IDC_BUTTON_START_SHEILD_UP      1072
#define IDC_EDIT_TIMER_MINUTE           1073
#define IDC_EDIT_TIMER_SECOND           1074
#define IDC_BUTTON_TIMER_START          1075
#define IDC_STATIC_TIMER_PICTURE        1076
#define IDC_STATIC_TIMER_EQUAL          1077
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
